version: '3.8'
name: an6

networks:
  an6:
    driver: bridge
    name: an6

services:
  postgres:
    container_name: an6_postgres
    image: postgres:13
    networks:
      - an6
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: an6
    ports:
      - 5432:5432
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - an6
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootpassword
    command: server --console-address ":9001" /data

volumes:
  postgres_volume:
  minio_storage: {}
